### ISSUE TITLE
Should we be using SQLite? (it's complicated)

### ISSUE THREAD

**Issue by tjlane** [pandegroup/msmaccelerator#4]
@rmcgibbo 

This would be better than having to install/deal with a full SQL database. Looks like we can still use SQL-Alchemy with minimal changes:

http://www.rmunn.com/sqlalchemy-tutorial/tutorial.html

Want to take a crack at changing us over? If not I'll try :). You're more familiar with the SQLdb part of the code, though.

**Comment by rmcgibbo** [comment]
There is a problem with sqlite and thread safety. Let's talk tomorrow

**Comment by tjlane** [comment]
OK too bad :(. I'll be in after lunch.

**Comment by rmcgibbo** [comment]
Here's my experience. I started by using SQLite3, and there are a lot of advantages. Basically MySQL is "heavy". It needs to be running concurrently as another process/service, and clearing the database and restarting is annoying. With SQLite, the whole database is just a single file, so you can keep the database file with the trajectory files and it's all very nice.

But I ran into a problem that I didn't know how to solve with SQLite3 related to concurrency. MSMAccelerator has two threads. There's the main thread that does most everything, and then the QMaster thread which blocks waiting for workqueue to return. Both of these threads read and write to the database, which turns out to be a killer. SQLite3 is apparently okay with multiple threads/sockets/processes concurrently reading from a database, but it locks when you have multiple concurrent writes.

The ways I see to solve this are (1) refactor such that the QMaster thread doesn't need to write to the DB (2) replace workqueue with something that is easier to use asynchronously. I guess we've got a lot invested in work queue, but I personally don't think it's that great. I think there _must_ be better solutions. (3) suck it up with workqueue/mysql. (4) find some other database/store.

**Comment by tjlane** [comment]
After googling around a little I think we could set up an SQLite DB that admits locks, such that one thread locks onto the DB and the other thread is forced to block until the lock is lifted. Why doesn't that work?

**Comment by rmcgibbo** [comment]
Yes, this probably should be possible. At least, I don't see why it shouldn't be. I'm not sure if this is the kind of thing that you do as a config option in sqlite3/sqlalchemy, or instead just manually manage a lock. I think it's probably #2. 

One way to do this is have every function that uses the database acquire/release the lock via a decorator. You have to be careful with this though. For instance, if you call one function that's wrapped `@with_db_lock` from within another function that is wrapped by `@with_db_lock`, the whole thing is going to just stop.

```
import functools
from threading import Lock

class QMaster(object):
    ...
    @with_db_lock
    def on_return(self, ...)
        ...


_session_lock = Lock()
def with_db_lock(f):
    @functools.wraps(f)
    def wrap(*args, **kwargs):
        _session_lock.acquire()
        try:
            f(*args, **kwargs)
        finally:
            _session_lock.release()
    return wrap
```

**Comment by rmcgibbo** [comment]
Okay, I've fixed the issue and we're using sqlite3 now.

basically, every method that uses the session really should have the @with_db_lock decorator

```
# from database.py

# @with_db_lock decorator 
# ======================== #
# this decorator is a little complicated, and is used to get around the fact
# that sqlite3 does not support concurrent access from multiple threads

# this decorator should be used by all functions that directly use the session
# object.

# first, in manages a reentrant lock associated with the database. only
# one thread can hold the lock at a time. This is actually probably not doing
# much, since we're already using a sqlalchemy "scoped session", which is supposed
# to do this already

# the second thing is that this decoractor runs a commit on the Session after
# the function exits. SORRY. this is definitly not the most IO efficient, but
# it appears to be necessary (empirically, i get a DB locking error if I don't
# have it). Basically, with SQLite, a transaction might still be open in the session
# even after the function finishes and the lock is released -- it has no idea that
# the function returned. But commit()ing seems to end the transaction.


_session_lock = threading.RLock()
def with_db_lock(f):
    @functools.wraps(f)
    def wrap(*args, **kwargs):
        #print 'Acquiring lock! %s' % threading.current_thread()
        _session_lock.acquire()
        try:
            return_value = f(*args, **kwargs)
        finally:
            #print 'Releasing Lock! %s' % threading.current_thread()
            Session.commit()
            _session_lock.release()
        return return_value
    return wrap
```
